export const FETCH_SUGGESTIONS_INIT = 'FETCH_SUGGESTIONS_INIT';
export const FETCH_SUGGESTIONS_SUCCESS = 'FETCH_USER_LIST_SUCCESS';
export const FETCH_SUGGESTIONS_FAILURE = 'FETCH_USER_LIST_FAILURE';

export const FETCH_SUGGESTION_DETAILS_INIT = 'FETCH_SUGGESTION_DETAILS_INIT';
export const FETCH_SUGGESTION_DETAILS_SUCCESS = 'FETCH_SUGGESTION_DETAILS_SUCCESS';
export const FETCH_SUGGESTION_DETAILS_FAILURE = 'FETCH_SUGGESTION_DETAILS_FAILURE';

export const DO_LIKE = 'DO_LIKE';
export const DO_UNLIKE = 'DO_UNLIKE';
export const DO_RESTORE_LAST_UNLIKED = 'DO_RESTORE_LAST_UNLIKED';

export const FETCH_LIKED_HISTORY = 'FETCH_LIKE_HISTORY';